In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!ls /content/drive/MyDrive/cosesmic/layers/pseudo__absense/

1.gpkg	final_ml_dataset.csv  non_landslides_1.csv
2.csv	landslides.csv	      non_landslides.csv

In [ ]:
import pandas as pd

In [ ]:
df_landslide = pd.read_csv(
    "/content/drive/MyDrive/cosesmic/layers/pseudo__absense/landslides.csv",encoding="latin1"
)

df_nonlandslide = pd.read_csv(
    "/content/drive/MyDrive/cosesmic/layers/pseudo__absense/non_landslides_11.csv",encoding="latin1"
)

/tmp/ipykernel_835/1563755003.py:1: DtypeWarning: Columns (5,7,23,25,26,40,44,52,53,57,58,63,64,71,72,73,74,76,77,78,79,80,82,84,85,86,87,88,91,94,100,101,102,103,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  df_landslide = pd.read_csv(

In [ ]:
df_nonlandslide.tail()

,fid,label,SAMPLE_ss1,X_COORD,Y_COORD,ASPECT_11,ELEVATION_11,PLAN_CURV_11,PROFILE_CURV_11,TWI_11,...,NDVI_11,LULC_11,PROXIMITY_ROADS_11,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,SLOPE_11,FLOW_ACC_11
14995,14996,0,2663.305664,280389.046,3432185.264,5,2663.305664,0.009523,0.001492,6.241909,...,0.123716,30,42.426407,33.136082,13490.330078,483.749847,100.733185,211.977676,0.500168,8.983902
14996,14997,0,3869.518555,347859.046,3405335.264,2,3869.518555,0.000038,-0.002511,12.759489,...,-0.030370,70,7637.047852,0.000000,1873.018921,736.062012,149.256714,322.005890,0.328898,15.030528
14997,14998,0,4899.723145,463329.046,3350645.264,5,4899.723145,0.002917,-0.000802,5.119618,...,0.013352,60,7173.200195,44.407207,3681.086914,558.708679,118.958084,260.967957,0.807069,8.509227
14998,14999,0,1759.636719,216429.046,3399635.264,4,1759.636719,0.106002,0.001943,5.608116,...,0.239515,30,295.465729,46.690472,2227.285400,902.890137,163.875565,398.753387,0.105254,6.707710
14999,15000,0,1330.141235,332559.046,3267995.264,6,1330.141235,-0.002745,0.000115,6.648925,...,0.459379,10,1838.831177,15.556349,2053.411865,923.284790,176.976685,438.317566,0.354079,8.999921

In [ ]:
df_landslide.head()

,gid,slide_no,latitude,longitude,communicat,persons_de,nh_sh_loca,people_aff,alert,abstract,...,PROXIMITY_ROADS_11,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD
0,19837,UK/CHA/53O15/2016/29,29.480917,79.984417,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.414214,2658.006836,529.694031,121.518135,258.144958,17.800678,1,401540.952,3261698.480
1,19839,UK/ALM/53O15/2016/48,29.481724,79.968877,NaN,NaN,NaN,NaN,NaN,NaN,...,108.166534,16.000000,3178.442871,547.740418,118.726166,252.454834,8.681055,1,400035.083,3261801.147
2,19840,UK/PIT/62C03/2016/112,29.483224,80.002729,NaN,NaN,NaN,NaN,NaN,NaN,...,60.000000,8.062258,1397.175781,529.694031,121.518135,258.144958,10.322898,1,403318.553,3261938.765
3,19842,UK/ALM/53O15/2016/37,29.484713,79.972357,NaN,NaN,NaN,NaN,NaN,NaN,...,240.000000,15.000000,2992.340332,529.694031,121.518135,258.144958,9.248116,1,400375.404,3262129.371
4,19843,UK/CHA/53O15/2016/36,29.484810,79.991369,NaN,NaN,NaN,NaN,NaN,NaN,...,108.166534,6.708204,1855.397583,529.694031,121.518135,258.144958,10.140306,1,402218.711,3262123.997

In [ ]:
df = pd.concat(
    [df_landslide, df_nonlandslide],
    ignore_index=True
)

In [ ]:
df['SLOPE_11'].tail()

31014    0.500168
31015    0.328898
31016    0.807069
31017    0.105254
31018    0.354079
Name: SLOPE_11, dtype: float64

In [ ]:
output_path = "/content/drive/MyDrive/cosesmic/layers/pseudo__absense/final_ml_dataset.csv"

In [ ]:
df.to_csv(output_path, index=False)

print("Combined shape:", df.shape)
print("Saved:", output_path)

Combined shape: (31019, 130)
Saved: /content/drive/MyDrive/cosesmic/layers/pseudo__absense/final_ml_dataset.csv

In [ ]:
df.head()

,gid,slide_no,latitude,longitude,communicat,persons_de,nh_sh_loca,people_aff,alert,abstract,...,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD,fid
0,19837.0,UK/CHA/53O15/2016/29,29.480917,79.984417,NaN,NaN,NaN,NaN,NaN,NaN,...,1.414214,2658.006836,529.694031,121.518135,258.144958,17.800678,1,401540.952,3261698.480,NaN
1,19839.0,UK/ALM/53O15/2016/48,29.481724,79.968877,NaN,NaN,NaN,NaN,NaN,NaN,...,16.000000,3178.442871,547.740418,118.726166,252.454834,8.681055,1,400035.083,3261801.147,NaN
2,19840.0,UK/PIT/62C03/2016/112,29.483224,80.002729,NaN,NaN,NaN,NaN,NaN,NaN,...,8.062258,1397.175781,529.694031,121.518135,258.144958,10.322898,1,403318.553,3261938.765,NaN
3,19842.0,UK/ALM/53O15/2016/37,29.484713,79.972357,NaN,NaN,NaN,NaN,NaN,NaN,...,15.000000,2992.340332,529.694031,121.518135,258.144958,9.248116,1,400375.404,3262129.371,NaN
4,19843.0,UK/CHA/53O15/2016/36,29.484810,79.991369,NaN,NaN,NaN,NaN,NaN,NaN,...,6.708204,1855.397583,529.694031,121.518135,258.144958,10.140306,1,402218.711,3262123.997,NaN

In [ ]:
!ls /content/drive/MyDrive/cosesmic/layers/random/

final_ml_dataset.csv	       pseudoabsence_sampling_area_v2.gpkg
nonlandslide_v2.csv	       slope_mask_15deg.tif
pseudi_absence_points_random   slope_mask_valid.gpkg
pseudo_absence_filtered.gpkg   utt.csv
pseudo_absence_points_v2.gpkg

In [ ]:
df_landslide = pd.read_csv(
    "/content/drive/MyDrive/cosesmic/layers/pseudo__absense/landslides.csv",encoding="latin1"
)

df_nonlandslide = pd.read_csv(
    "/content/drive/MyDrive/cosesmic/layers/random/nonlandslide_v2.csv",encoding="latin1"
)

/tmp/ipykernel_5306/2212631546.py:1: DtypeWarning: Columns (5,7,23,25,26,40,44,52,53,57,58,63,64,71,72,73,74,76,77,78,79,80,82,84,85,86,87,88,91,94,100,101,102,103,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  df_landslide = pd.read_csv(

In [ ]:
print(df_landslide.columns[-17:])
print(df_nonlandslide.columns)

Index(['SLOPE_11', 'PLAN_CURV_11', 'PROFILE_CURV_11', 'TWI_11', 'TRI_11',
       'NDVI_11', 'LULC_11', 'PROXIMITY_ROADS_11', 'PROXIMITY_RIVERS_11',
       'PROXIMITY_FAULTS_11', 'MAX_RAINFALL_11', 'MEAN_RAINFALL_11',
       'MONSOON_RAINFALL_11', 'FLOW_ACC_11', 'label', 'X_COORD', 'Y_COORD'],
      dtype='object')
Index(['fid', 'label', 'ASPECT_11', 'ELEVATION_11', 'SLOPE_1', 'PLAN_CURV_11',
       'PROFILE_CURV_11', 'TWI_11', 'TRI_11', 'NDVI_11', 'LULC_11',
       'PROXIMITY_ROADS_11', 'PROXIMITY_RIVERS_11', 'PROXIMITY_FAULTS_11',
       'MAX_RAINFALL_11', 'MEAN_RAINFALL_11', 'MEAN_RAINFALL_11_2',
       'FLOW_ACC_11', 'X_COORD', 'Y_COORD'],
      dtype='object')

In [ ]:
df_nonlandslide = df_nonlandslide.rename(columns={
    "SLOPE_1": "SLOPE_11",
    "MEAN_RAINFALL_11_2": "MONSOON_RAINFALL_11"
})

In [ ]:
df = pd.concat(
    [df_landslide, df_nonlandslide],
    ignore_index=True
)

In [ ]:
output_path = "/content/drive/MyDrive/cosesmic/layers/random/final_ml_dataset.csv"

In [ ]:
df.to_csv(output_path, index=False)

print("Combined shape:", df.shape)
print("Saved:", output_path)

Combined shape: (30197, 129)
Saved: /content/drive/MyDrive/cosesmic/layers/random/final_ml_dataset.csv