In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!ls /content/drive/MyDrive/cosesmic/layers/

ls: cannot access '/content/drive/MyDrive/cosesmic/layers/': No such file or directory

In [ ]:
df = pd.read_csv(
    "/content/drive/MyDrive/cosesmic/layers/pseudo__absense/final_ml_dataset.csv",
    encoding="latin1",
    low_memory=False
)

In [ ]:
df['SLOPE_11'].tail()

31014    0.500168
31015    0.328898
31016    0.807069
31017    0.105254
31018    0.354079
Name: SLOPE_11, dtype: float64

In [ ]:
print(df.shape)

df.head()

(31019, 130)

,gid,slide_no,latitude,longitude,communicat,persons_de,nh_sh_loca,people_aff,alert,abstract,...,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD,fid,SAMPLE_ss1
0,19837.0,UK/CHA/53O15/2016/29,29.480917,79.984417,NaN,NaN,NaN,NaN,NaN,NaN,...,2658.006836,529.694031,121.518135,258.144958,17.800678,1,401540.952,3261698.480,NaN,NaN
1,19839.0,UK/ALM/53O15/2016/48,29.481724,79.968877,NaN,NaN,NaN,NaN,NaN,NaN,...,3178.442871,547.740418,118.726166,252.454834,8.681055,1,400035.083,3261801.147,NaN,NaN
2,19840.0,UK/PIT/62C03/2016/112,29.483224,80.002729,NaN,NaN,NaN,NaN,NaN,NaN,...,1397.175781,529.694031,121.518135,258.144958,10.322898,1,403318.553,3261938.765,NaN,NaN
3,19842.0,UK/ALM/53O15/2016/37,29.484713,79.972357,NaN,NaN,NaN,NaN,NaN,NaN,...,2992.340332,529.694031,121.518135,258.144958,9.248116,1,400375.404,3262129.371,NaN,NaN
4,19843.0,UK/CHA/53O15/2016/36,29.484810,79.991369,NaN,NaN,NaN,NaN,NaN,NaN,...,1855.397583,529.694031,121.518135,258.144958,10.140306,1,402218.711,3262123.997,NaN,NaN

In [ ]:
print(df.columns)

Index(['gid', 'slide_no', 'latitude', 'longitude', 'communicat', 'persons_de',
       'nh_sh_loca', 'people_aff', 'alert', 'abstract',
       ...
       'PROXIMITY_FAULTS_11', 'MAX_RAINFALL_11', 'MEAN_RAINFALL_11',
       'MONSOON_RAINFALL_11', 'FLOW_ACC_11', 'label', 'X_COORD', 'Y_COORD',
       'fid', 'SAMPLE_ss1'],
      dtype='object', length=130)

In [ ]:
keep_cols = [
    "ASPECT_11",
    "ELEVATION_11",
    "SLOPE_11",
    "PLAN_CURV_11",
    "PROFILE_CURV_11",
    "TWI_11",
    "TRI_11",
    "NDVI_11",
    "LULC_11",
    "PROXIMITY_ROADS_11",
    "PROXIMITY_RIVERS_11",
    "PROXIMITY_FAULTS_11",
    "MAX_RAINFALL_11",
    "MEAN_RAINFALL_11",
    "MONSOON_RAINFALL_11",
    "FLOW_ACC_11",
    "label",
    "X_COORD",
    "Y_COORD"
]

In [ ]:
df = df[keep_cols]

df.tail()

,ASPECT_11,ELEVATION_11,SLOPE_11,PLAN_CURV_11,PROFILE_CURV_11,TWI_11,TRI_11,NDVI_11,LULC_11,PROXIMITY_ROADS_11,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD
31014,5,2663.305664,0.500168,0.009523,0.001492,6.241909,10.177073,0.123716,30,42.426407,33.136082,13490.330078,483.749847,100.733185,211.977676,8.983902,0,280389.046,3432185.264
31015,2,3869.518555,0.328898,0.000038,-0.002511,12.759489,6.389220,-0.030370,70,7637.047852,0.000000,1873.018921,736.062012,149.256714,322.005890,15.030528,0,347859.046,3405335.264
31016,5,4899.723145,0.807069,0.002917,-0.000802,5.119618,18.857862,0.013352,60,7173.200195,44.407207,3681.086914,558.708679,118.958084,260.967957,8.509227,0,463329.046,3350645.264
31017,4,1759.636719,0.105254,0.106002,0.001943,5.608116,5.148562,0.239515,30,295.465729,46.690472,2227.285400,902.890137,163.875565,398.753387,6.707710,0,216429.046,3399635.264
31018,6,1330.141235,0.354079,-0.002745,0.000115,6.648925,6.764572,0.459379,10,1838.831177,15.556349,2053.411865,923.284790,176.976685,438.317566,8.999921,0,332559.046,3267995.264

In [ ]:
print(df.isnull().sum())

ASPECT_11                0
ELEVATION_11             0
SLOPE_11                 0
PLAN_CURV_11             0
PROFILE_CURV_11          0
TWI_11                   0
TRI_11                   0
NDVI_11                  0
LULC_11                  0
PROXIMITY_ROADS_11       0
PROXIMITY_RIVERS_11      0
PROXIMITY_FAULTS_11      1
MAX_RAINFALL_11        238
MEAN_RAINFALL_11       238
MONSOON_RAINFALL_11    238
FLOW_ACC_11              0
label                    0
X_COORD                  0
Y_COORD                  0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
print(df.isnull().sum())

print(df.shape)

ASPECT_11              0
ELEVATION_11           0
SLOPE_11               0
PLAN_CURV_11           0
PROFILE_CURV_11        0
TWI_11                 0
TRI_11                 0
NDVI_11                0
LULC_11                0
PROXIMITY_ROADS_11     0
PROXIMITY_RIVERS_11    0
PROXIMITY_FAULTS_11    0
MAX_RAINFALL_11        0
MEAN_RAINFALL_11       0
MONSOON_RAINFALL_11    0
FLOW_ACC_11            0
label                  0
X_COORD                0
Y_COORD                0
dtype: int64
(30781, 19)

In [ ]:
print(df.shape)

print(df["label"].value_counts())

(30781, 19)
label
1    15913
0    14868
Name: count, dtype: int64

In [ ]:
df.loc[16000]

ASPECT_11              5.000000e+00
ELEVATION_11           2.552562e+03
SLOPE_11               2.300511e-01
PLAN_CURV_11          -6.785934e-03
PROFILE_CURV_11       -1.485484e-03
TWI_11                 7.007758e+00
TRI_11                 4.363043e+00
NDVI_11                9.316078e-02
LULC_11                3.000000e+01
PROXIMITY_ROADS_11     3.014962e+02
PROXIMITY_RIVERS_11    2.236068e+00
PROXIMITY_FAULTS_11    4.249847e+03
MAX_RAINFALL_11        6.856616e+02
MEAN_RAINFALL_11       1.447699e+02
MONSOON_RAINFALL_11    3.024109e+02
FLOW_ACC_11            8.902353e+00
label                  1.000000e+00
X_COORD                2.554177e+05
Y_COORD                3.429156e+06
Name: 16000, dtype: float64

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/cosesmic/csv/final_ml_dataset_clean.csv",
    index=False
)

In [ ]:
df = pd.read_csv(
    "/content/drive/MyDrive/cosesmic/layers/random/final_ml_dataset.csv",
    encoding="latin1",
    low_memory=False
)

In [ ]:
df.tail()

,gid,slide_no,latitude,longitude,communicat,persons_de,nh_sh_loca,people_aff,alert,abstract,...,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD,fid
30192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.203604,108.166534,779.004211,157.726700,368.423889,9.544151,0,391899.0456,3298625.264,14995.0
30193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.669872,84.852814,871.823181,171.792160,395.586151,10.012309,0,457029.0456,3331535.264,14997.0
30194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49.406479,3842.459961,401.168335,98.875710,218.056992,11.127522,0,278919.0456,3349895.264,14998.0
30195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.000000,2925.269043,1022.315918,194.387741,476.700623,9.927781,0,346929.0456,3261005.264,14999.0
30196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.000000,1332.216187,714.237488,150.275803,317.685791,7.636580,0,345069.0456,3380345.264,15000.0

In [ ]:
print(df.shape)

df.head()

(30197, 129)

,gid,slide_no,latitude,longitude,communicat,persons_de,nh_sh_loca,people_aff,alert,abstract,...,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD,fid
0,19837.0,UK/CHA/53O15/2016/29,29.480917,79.984417,NaN,NaN,NaN,NaN,NaN,NaN,...,1.414214,2658.006836,529.694031,121.518135,258.144958,17.800678,1,401540.952,3261698.480,NaN
1,19839.0,UK/ALM/53O15/2016/48,29.481724,79.968877,NaN,NaN,NaN,NaN,NaN,NaN,...,16.000000,3178.442871,547.740418,118.726166,252.454834,8.681055,1,400035.083,3261801.147,NaN
2,19840.0,UK/PIT/62C03/2016/112,29.483224,80.002729,NaN,NaN,NaN,NaN,NaN,NaN,...,8.062258,1397.175781,529.694031,121.518135,258.144958,10.322898,1,403318.553,3261938.765,NaN
3,19842.0,UK/ALM/53O15/2016/37,29.484713,79.972357,NaN,NaN,NaN,NaN,NaN,NaN,...,15.000000,2992.340332,529.694031,121.518135,258.144958,9.248116,1,400375.404,3262129.371,NaN
4,19843.0,UK/CHA/53O15/2016/36,29.484810,79.991369,NaN,NaN,NaN,NaN,NaN,NaN,...,6.708204,1855.397583,529.694031,121.518135,258.144958,10.140306,1,402218.711,3262123.997,NaN

In [ ]:
keep_cols = [
    "ASPECT_11",
    "ELEVATION_11",
    "SLOPE_11",
    "PLAN_CURV_11",
    "PROFILE_CURV_11",
    "TWI_11",
    "TRI_11",
    "NDVI_11",
    "LULC_11",
    "PROXIMITY_ROADS_11",
    "PROXIMITY_RIVERS_11",
    "PROXIMITY_FAULTS_11",
    "MAX_RAINFALL_11",
    "MEAN_RAINFALL_11",
    "MONSOON_RAINFALL_11",
    "FLOW_ACC_11",
    "label",
    "X_COORD",
    "Y_COORD"
]

In [ ]:
df = df[keep_cols]

df.head()

,ASPECT_11,ELEVATION_11,SLOPE_11,PLAN_CURV_11,PROFILE_CURV_11,TWI_11,TRI_11,NDVI_11,LULC_11,PROXIMITY_ROADS_11,PROXIMITY_RIVERS_11,PROXIMITY_FAULTS_11,MAX_RAINFALL_11,MEAN_RAINFALL_11,MONSOON_RAINFALL_11,FLOW_ACC_11,label,X_COORD,Y_COORD
0,3.0,679.130005,0.276021,-0.016538,-0.008122,15.716049,7.545804,0.160194,30.0,0.000000,1.414214,2658.006836,529.694031,121.518135,258.144958,17.800678,1,401540.952,3261698.480
1,4.0,913.332825,0.632032,0.000268,-0.000074,5.646492,13.151764,0.295511,30.0,108.166534,16.000000,3178.442871,547.740418,118.726166,252.454834,8.681055,1,400035.083,3261801.147
2,8.0,721.089966,0.681697,-0.008121,0.000211,7.185718,14.802107,0.268077,10.0,60.000000,8.062258,1397.175781,529.694031,121.518135,258.144958,10.322898,1,403318.553,3261938.765
3,3.0,758.113342,0.561121,-0.002347,-0.000685,6.366368,11.326160,0.243862,30.0,240.000000,15.000000,2992.340332,529.694031,121.518135,258.144958,9.248116,1,400375.404,3262129.371
4,2.0,731.924133,0.589670,-0.007241,0.001289,7.196071,12.147046,0.338092,30.0,108.166534,6.708204,1855.397583,529.694031,121.518135,258.144958,10.140306,1,402218.711,3262123.997

In [ ]:
print(df.isnull().sum())

ASPECT_11                2
ELEVATION_11             2
SLOPE_11                 2
PLAN_CURV_11             2
PROFILE_CURV_11          2
TWI_11                   2
TRI_11                   2
NDVI_11                  1
LULC_11                  1
PROXIMITY_ROADS_11       4
PROXIMITY_RIVERS_11      1
PROXIMITY_FAULTS_11      3
MAX_RAINFALL_11        296
MEAN_RAINFALL_11       296
MONSOON_RAINFALL_11    296
FLOW_ACC_11              2
label                    0
X_COORD                  0
Y_COORD                  0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
print(df.isnull().sum())

print(df.shape)

ASPECT_11              0
ELEVATION_11           0
SLOPE_11               0
PLAN_CURV_11           0
PROFILE_CURV_11        0
TWI_11                 0
TRI_11                 0
NDVI_11                0
LULC_11                0
PROXIMITY_ROADS_11     0
PROXIMITY_RIVERS_11    0
PROXIMITY_FAULTS_11    0
MAX_RAINFALL_11        0
MEAN_RAINFALL_11       0
MONSOON_RAINFALL_11    0
FLOW_ACC_11            0
label                  0
X_COORD                0
Y_COORD                0
dtype: int64
(29899, 19)

In [ ]:
print(df["label"].value_counts())

label
1    15913
0    13986
Name: count, dtype: int64

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/cosesmic/csv/final_ml_dataset_clean_random.csv",
    index=False
)